language: "node_js"
node_js:
  - "14"
install:
  - "npm install -g gitbook"
  - "npm install -g gitbook-cli"
branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/shln21/blogs.git
script:
  - bash summary_create.sh
  - travis_wait 100 bash deploy.sh
